# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23 AS builder

WORKDIR /workspace
COPY . .
RUN CGO_ENABLED=1 GOFLAGS="" go build --installsuffix cgo

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /workspace/kube-rbac-proxy /usr/local/bin/kube-rbac-proxy
EXPOSE 8080
USER 65532:65532

ENTRYPOINT ["/usr/local/bin/kube-rbac-proxy"]

LABEL com.redhat.component="kube-rbac-proxy" \
name="kube-rbac-proxy" \
summary="kube-rbac-proxy" \
io.openshift.expose-services="" \
io.openshift.tags="data,images" \
io.k8s.display-name="kube-rbac-proxy" \
maintainer="" \
description="kube-rbac-proxy" \
io.k8s.description="kube-rbac-proxy"

